# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#


version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install --pure-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
             - ~/repo
      - run: yarn test

  flow:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn flow:check

  test:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn coverage
      - run: cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

  test_dist:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn build
      - run: yarn test:dist

  lint:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn lint


workflows:
  version: 2
  build-and-test:
    jobs:
      - install:
      - flow:
          requires:
            - install
      - test:
          requires:
            - install
      - test_dist:
          requires:
            - install
      - lint:
          requires:
            - install
